kind: Deployment
apiVersion: apps/v1
metadata:
  name: ci-cd-jenk-docker
  namespace: default
  uid: dc591ed0-d866-429d-910f-9a17cfb6f824
  resourceVersion: '3103'
  generation: 2
  creationTimestamp: '2021-09-05T08:35:37Z'
  labels:
    k8s-app: ci-cd-jenk-docker
  annotations:
    deployment.kubernetes.io/revision: '2'
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: apps/v1
      time: '2021-09-05T08:35:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:k8s-app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:k8s-app': {}
              'f:name': {}
            'f:spec':
              'f:containers':
                'k:{"name":"ci-cd-jenk-docker"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:resources': {}
                  'f:securityContext':
                    .: {}
                    'f:privileged': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-09-05T09:10:49Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      subresource: status
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ci-cd-jenk-docker
  template:
    metadata:
      name: ci-cd-jenk-docker
      creationTimestamp: null
      labels:
        k8s-app: ci-cd-jenk-docker
    spec:
      containers:
        - name: ci-cd-jenk-docker
          image: shubhamaggarwal02/ci-cd-jenkins-docker-integration
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
  - type: Available
      status: 'False'
      lastUpdateTime: '2021-09-05T09:10:49Z'
      lastTransitionTime: '2021-09-05T09:10:49Z'
      reason: MinimumReplicasAvailable
      message: Deployment have minimum availability.
      - type: Progressing
        status: 'True'
        lastUpdateTime: '2021-09-05T09:08:57Z'
        lastTransitionTime: '2021-09-05T09:05:42Z'
        reason: NewReplicaSetAvailable
        message: ReplicaSet "ci-cd-jenk-docker-6646488457" has successfully progressed.
